<x-admin-layout title="Penyesuaian Stok">
<div class="mx-auto max-w-3xl space-y-8">
    <div><a href="{{ route('admin.inventory.show', $product) }}" class="text-sm font-bold text-emerald-700">← Kembali ke riwayat</a><p class="mt-6 text-xs font-bold uppercase tracking-[0.2em] text-emerald-600">Inventory operation</p><h1 class="mt-2 text-4xl font-black tracking-tight text-slate-950">Sesuaikan stok</h1><p class="mt-2 text-sm leading-6 text-slate-500">Gunakan adjustment untuk mencatat hasil opname, koreksi penerimaan, atau selisih stok fisik.</p></div>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><p class="font-bold">Periksa kembali input berikut:</p><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ route('admin.inventory.adjust.store', $product) }}" class="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">@csrf
        <div class="flex items-center gap-4 rounded-2xl bg-slate-950 p-5 text-white"><div class="flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-500 text-lg font-black">{{ strtoupper(substr($product->name, 0, 2)) }}</div><div><p class="text-sm text-slate-400">Produk yang dipilih</p><p class="text-xl font-black">{{ $product->name }}</p><p class="mt-1 text-xs text-slate-400">Stok saat ini {{ number_format($product->stock) }} unit</p></div></div>
        <div class="grid gap-5 sm:grid-cols-2"><label><span class="text-sm font-bold text-slate-700">Stok baru</span><div class="relative mt-2"><input type="number" name="new_stock" min="0" max="9999999" value="{{ old('new_stock', $product->stock) }}" required class="w-full rounded-xl border-slate-200 bg-slate-50 px-4 py-3 pr-16 text-lg font-bold outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100"><span class="pointer-events-none absolute right-4 top-3.5 text-sm text-slate-400">unit</span></div></label><div class="rounded-xl bg-slate-50 p-4"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Perubahan</p><p class="mt-2 text-2xl font-black text-slate-950">Akan dihitung otomatis</p><p class="mt-1 text-xs leading-5 text-slate-500">Ledger menyimpan stok sebelum, sesudah, dan delta.</p></div></div>
        <label class="block"><span class="text-sm font-bold text-slate-700">Alasan adjustment</span><textarea name="note" rows="4" required maxlength="255" placeholder="Contoh: Opname gudang 20 Agustus 2026 — ditemukan selisih 3 unit." class="mt-2 w-full resize-none rounded-xl border-slate-200 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100">{{ old('note') }}</textarea><span class="mt-2 block text-xs text-slate-400">Wajib diisi agar setiap perubahan dapat diaudit.</span></label>
        <div class="flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><a href="{{ route('admin.inventory.show', $product) }}" class="rounded-xl px-5 py-3 text-center text-sm font-bold text-slate-600 hover:bg-slate-100">Batal</a><button class="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white shadow-sm hover:bg-emerald-700">Simpan adjustment</button></div>
    </form>
</div>
</x-admin-layout>
