<x-admin-layout title="Inventory Control">
<div class="space-y-8">
    <header class="flex flex-col justify-between gap-5 lg:flex-row lg:items-end">
        <div><p class="text-xs font-bold uppercase tracking-[0.2em] text-emerald-600">Stock operations</p><h1 class="mt-2 text-4xl font-black tracking-tight text-slate-950">Inventory control</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Pantau ketersediaan, lakukan koreksi stok, dan telusuri setiap perubahan dengan ledger yang selalu tercatat.</p></div>
        <a href="{{ route('admin.products.create') }}" class="inline-flex items-center justify-center rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-emerald-700">+ Tambah produk</a>
    </header>
    @if(session('success'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('success') }}</div>@endif
    @if(session('error'))<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{{ session('error') }}</div>@endif
    @php($lowStock = \App\Models\Product::whereRaw('stock <= low_stock_threshold')->count())
    @php($totalUnits = \App\Models\Product::sum('stock'))
    @php($totalProducts = \App\Models\Product::count())
    <section class="grid gap-4 md:grid-cols-3">
        <div class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Total produk</p><span class="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold text-slate-500">CATALOG</span></div><p class="mt-5 text-3xl font-black tabular-nums">{{ number_format($totalProducts) }}</p><p class="mt-1 text-sm text-slate-500">SKU aktif di katalog</p></div>
        <div class="rounded-2xl border border-emerald-100 bg-emerald-50 p-5"><div class="flex items-start justify-between"><p class="text-xs font-bold uppercase tracking-wider text-emerald-700">Total unit</p><span class="rounded-lg bg-white/70 px-2 py-1 text-xs font-bold text-emerald-700">ON HAND</span></div><p class="mt-5 text-3xl font-black tabular-nums text-emerald-950">{{ number_format($totalUnits) }}</p><p class="mt-1 text-sm text-emerald-700">Stok fisik tercatat</p></div>
        <div class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><div class="flex items-start justify-between"><p class="text-xs font-bold uppercase tracking-wider text-amber-700">Perlu perhatian</p><span class="rounded-lg bg-white/70 px-2 py-1 text-xs font-bold text-amber-700">LOW STOCK</span></div><p class="mt-5 text-3xl font-black tabular-nums text-amber-950">{{ number_format($lowStock) }}</p><p class="mt-1 text-sm text-amber-700">Produk di bawah threshold</p></div>
    </section>
    <form class="flex flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:flex-row"><div class="relative flex-1"><svg class="absolute left-4 top-3.5 h-4 w-4 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m21 21-4.35-4.35m2.35-5.65a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z"/></svg><input name="search" value="{{ request('search') }}" placeholder="Cari produk atau SKU..." class="w-full rounded-xl border-0 bg-slate-50 py-3 pl-11 pr-4 text-sm outline-none ring-1 ring-slate-200 focus:ring-2 focus:ring-emerald-500"></div><label class="flex items-center gap-3 rounded-xl bg-slate-50 px-4 text-sm font-semibold text-slate-600"><input type="checkbox" name="low_stock_only" value="1" @checked(request('low_stock_only')) class="h-4 w-4 rounded border-slate-300 text-emerald-600"> Hanya stok rendah</label><button class="rounded-xl bg-slate-800 px-5 py-3 text-sm font-bold text-white hover:bg-slate-700">Filter</button></form>
    <div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="hidden grid-cols-[2fr_1fr_1fr_auto] gap-4 border-b border-slate-100 bg-slate-50 px-6 py-3 text-[11px] font-bold uppercase tracking-wider text-slate-400 md:grid"><span>Produk</span><span>Stok saat ini</span><span>Status</span><span>Aksi</span></div>
    @forelse($products as $product)<div class="grid gap-4 border-b border-slate-100 px-6 py-5 last:border-0 md:grid-cols-[2fr_1fr_1fr_auto] md:items-center {{ $product->stock <= $product->low_stock_threshold ? 'bg-amber-50/40' : '' }}"><div class="flex items-center gap-4"><div class="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-slate-100 text-xs font-bold text-slate-400">@if($product->image)<img src="{{ $product->image }}" alt="{{ $product->name }}" class="h-full w-full object-cover">@else{{ strtoupper(substr($product->name, 0, 2)) }}@endif</div><div><p class="text-xs text-slate-400">{{ $product->category?->name ?? 'Tanpa kategori' }}</p><p class="font-bold text-slate-950">{{ $product->name }}</p><p class="mt-1 text-xs text-slate-500">Rp{{ number_format($product->price, 0, ',', '.') }}</p></div></div><div><span class="text-xs text-slate-400 md:hidden">Stok saat ini</span><p class="font-mono text-xl font-black tabular-nums {{ $product->stock <= $product->low_stock_threshold ? 'text-amber-700' : 'text-slate-950' }}">{{ number_format($product->stock) }} <span class="font-sans text-xs font-semibold text-slate-400">unit</span></p></div><div><span class="inline-flex rounded-full px-3 py-1 text-xs font-bold {{ $product->stock <= $product->low_stock_threshold ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-700' }}">{{ $product->stock <= $product->low_stock_threshold ? 'Perlu restock' : 'Aman' }}</span><p class="mt-1 text-xs text-slate-400">Threshold {{ $product->low_stock_threshold }}</p></div><div class="flex gap-2"><a href="{{ route('admin.inventory.show', $product) }}" class="rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700 hover:bg-slate-200">Riwayat</a><a href="{{ route('admin.inventory.adjust', $product) }}" class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white hover:bg-emerald-700">Sesuaikan</a></div></div>@empty<div class="px-6 py-16 text-center"><p class="font-bold text-slate-700">Produk tidak ditemukan</p><p class="mt-1 text-sm text-slate-500">Coba ubah kata kunci pencarian.</p></div>@endforelse</div>
    <div>{{ $products->links() }}</div>
</div>
</x-admin-layout>
