<x-admin-layout title="Staff">
    <div class="flex flex-col gap-6">
        <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end">
            <div><p class="text-sm font-semibold uppercase tracking-widest text-emerald-600">Access control</p><h1 class="mt-1 text-3xl font-black tracking-tight">Manajemen Staff</h1><p class="mt-1 text-sm text-slate-500">Kelola kasir dan barista tanpa menghapus histori transaksi.</p></div>
            @if(session('success')) <div class="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">{{ session('success') }}</div> @endif
        </div>
        <div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
                <form class="flex gap-3 border-b border-slate-100 p-4" method="GET"><input name="search" value="{{ request('search') }}" class="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2 text-sm outline-none focus:border-emerald-500" placeholder="Cari nama staff..."><button class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Cari</button></form>
                <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">Nama</th><th class="px-5 py-3">Role</th><th class="px-5 py-3">Status</th><th class="px-5 py-3 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
                    @forelse($staff as $user)<tr><td class="px-5 py-4"><form method="POST" action="{{ route('admin.users.update', $user) }}" class="flex flex-wrap items-center gap-2">@csrf @method('PUT')<input name="name" value="{{ $user->name }}" required class="w-32 rounded-lg border border-slate-200 px-2 py-1.5 text-sm font-bold"><select name="role" class="rounded-lg border border-slate-200 px-2 py-1.5 text-xs"><option value="cashier" @selected($user->role === 'cashier')>Kasir</option><option value="barista" @selected($user->role === 'barista')>Barista</option></select><button class="rounded-lg bg-slate-100 px-2.5 py-1.5 text-xs font-bold text-slate-700">Simpan</button></form></td><td class="px-5 py-4 capitalize text-slate-600">{{ $user->role }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $user->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $user->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="px-5 py-4"><div class="flex flex-wrap justify-end gap-2"><form method="POST" action="{{ route('admin.users.reset-pin', $user) }}" class="flex gap-1">@csrf @method('PATCH')<input name="pin" required pattern="[0-9]{4,6}" class="w-24 rounded-lg border border-slate-200 px-2 py-1.5 text-xs" placeholder="PIN baru"><button class="rounded-lg bg-amber-100 px-2.5 py-1.5 text-xs font-bold text-amber-800">Reset PIN</button></form>@if($user->is_active)<form method="POST" action="{{ route('admin.users.deactivate', $user) }}">@csrf @method('PATCH')<button class="rounded-lg bg-red-50 px-2.5 py-1.5 text-xs font-bold text-red-700">Nonaktifkan</button></form>@else<form method="POST" action="{{ route('admin.users.activate', $user) }}">@csrf @method('PATCH')<button class="rounded-lg bg-emerald-50 px-2.5 py-1.5 text-xs font-bold text-emerald-700">Aktifkan</button></form>@endif</div></td></tr>@empty<tr><td colspan="4" class="px-5 py-12 text-center text-slate-500">Belum ada staff kasir atau barista.</td></tr>@endforelse
                </tbody></table></div><div class="p-4">{{ $staff->links() }}</div>
            </section>
            <section class="h-fit rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-black">Tambah staff</h2><form class="mt-5 space-y-4" method="POST" action="{{ route('admin.users.store') }}">@csrf<label class="block text-sm font-semibold">Nama<input name="name" required value="{{ old('name') }}" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><label class="block text-sm font-semibold">Role<select name="role" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="cashier">Kasir</option><option value="barista">Barista</option></select></label><label class="block text-sm font-semibold">PIN awal<input name="pin" required pattern="[0-9]{4,6}" inputmode="numeric" class="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5"></label><button class="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-700">Tambah Staff</button></form>@if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif</section>
        </div>
    </div>
</x-admin-layout>
