<div class="space-y-6">
    <form wire:submit="save" class="grid gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-5">
        <div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-slate-500">Tanggal</label><input wire:model="date" type="date" class="w-full rounded-lg border-slate-300"></div>
        <div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-slate-500">Kategori</label><input wire:model="category" class="w-full rounded-lg border-slate-300"></div>
        <div class="md:col-span-2"><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-slate-500">Deskripsi</label><input wire:model="description" placeholder="Contoh: Gas dapur" class="w-full rounded-lg border-slate-300"></div>
        <div><label class="mb-1 block text-xs font-bold uppercase tracking-wide text-slate-500">Jumlah</label><input wire:model="amount" type="number" min="1" step="0.01" class="w-full rounded-lg border-slate-300"></div>
        <div class="md:col-span-5 flex justify-end"><button class="rounded-lg bg-emerald-600 px-5 py-2.5 text-sm font-bold text-white hover:bg-emerald-700">Simpan expense</button></div>
        @error('*')<p class="text-sm text-red-600 md:col-span-5">{{ $message }}</p>@enderror
    </form>
    <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-5"><h2 class="font-bold">Riwayat expense</h2><input wire:model.live.debounce.300ms="search" placeholder="Cari expense..." class="rounded-lg border-slate-300 text-sm"></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-3">Nomor</th><th class="px-5 py-3">Tanggal</th><th class="px-5 py-3">Kategori</th><th class="px-5 py-3">Deskripsi</th><th class="px-5 py-3 text-right">Jumlah</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($expenses as $expense)<tr><td class="px-5 py-4 font-semibold">{{ $expense->expense_number }}</td><td class="px-5 py-4">{{ $expense->expense_date->format('d/m/Y') }}</td><td class="px-5 py-4">{{ $expense->category }}</td><td class="px-5 py-4">{{ $expense->description }}</td><td class="px-5 py-4 text-right font-mono font-semibold">Rp{{ number_format($expense->amount, 0, ',', '.') }}</td><td class="px-5 py-4 text-right"><button wire:click="delete({{ $expense->id }})" wire:confirm="Hapus expense ini?" class="text-sm font-bold text-red-600">Hapus</button></td></tr>@empty<tr><td colspan="6" class="px-5 py-8 text-center text-slate-500">Belum ada expense.</td></tr>@endforelse</tbody></table></div><div class="p-5">{{ $expenses->links() }}</div></section>
</div>
